skip_tags: true

version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017"
  PLATFORM_TOOLSET: v141_xp

build:
  project: .\cqsocketapi.sln
  verbosity: minimal

artifacts:
  - path: Release\me.cqp.ishisashi.cqsocketapi.dll
    name: cqsocketapi dll
