skip_tags: true
version: '{branch} build {build}'
configuration: Release

build:
  project: .\cqsocketapi.sln
  verbosity: minimal

artifacts:
  - path: Release\me.cqp.ishisashi.cqsocketapi.dll
    name: cqsocketapi dll
