skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017
configuration: Release

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017"
  PLATFORM_TOOLSET: v141_xp

build:
  project: .\cqsocketapi.sln
  verbosity: minimal

artifacts:
  - path: Release\me.cqp.ishisashi.cqsocketapi.dll
    name: cqsocketapi dll
