skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2019
configuration: Release

build:
  project: .\cqsocketapi.sln
  verbosity: minimal

artifacts:
  - path: Release\me.cqp.ishisashi.cqsocketapi.dll
    name: cqsocketapi dll
